### ISSUE TITLE
It would be nice if "Filter line by ..." will have some patterns history.

### ISSUE THREAD

**Issue by gost-serb** [everettjf/vscode-filter-line#11]
Of course, if it's possible)

**Comment by everettjf** [comment]
Yes, it could be. But I thought it maybe too complex for such a simple tool.
Thanks for your proposal.
Sorry for that I won't add this feature.
:)

**Comment by gost-serb** [comment]
Sadly, I thought it something like store to some cache file last N filters, that was used by each filter type and than just show them to user. If you don't mind I can try to implement this and create pull request

**Comment by everettjf** [comment]
Of course, welcome pull request.
