### ISSUE TITLE
Filtering by Regex (Not in line)

### ISSUE THREAD

**Issue by jcb871** [everettjf/vscode-filter-line#2]
Could you please provide a sample regex to get lines not containing a word?

**Comment by everettjf** [comment]
Seems like that it's not easy to write such a regex. ( https://stackoverflow.com/questions/406230/regular-expression-to-match-a-line-that-doesnt-contain-a-word )

But it's easy to provide a command such as "Filter Line By Not Contain String" and "Filter Line By  Not Match Regex", I will work on it.

**Comment by everettjf** [comment]
@jcb871 Update the extension and you will see below:
![image](https://user-images.githubusercontent.com/1665109/42586955-e432d5ec-856b-11e8-9b83-6cf73df79a27.png)
