### ISSUE TITLE
Hi GOST-UA ,there is some bugs in the PR

### ISSUE THREAD

**Issue by everettjf** [everettjf/vscode-filter-line#21]
https://github.com/everettjf/vscode-filter-line/pull/19

Hi, @GOST-UA 
I found that the basic filter string not work after I merged and published.
So I rollback the master code to version 1.5.1 and republish it to 2.0.1

The branch dev (https://github.com/everettjf/vscode-filter-line/tree/dev) contains your code. You could debug :)
I will focus on the dev these days maybe~

Sorry for that.

**Comment by gost-serb** [comment]
OK, I'll try debug today, if not I will continue on Monday

**Comment by gost-serb** [comment]
I just tried to reproduce this issue and it works. Could you provide some additional info: OS which you used, logs from FilterLine Output, maybe sample file.

**Comment by everettjf** [comment]
any file that already saved on disk. Do you have telegram account? add me if you have. My account is everettjf

________________________________

**Comment by everettjf** [comment]
os: macOS
![image](https://user-images.githubusercontent.com/1665109/74154945-9ccc0d80-4c4e-11ea-943d-6e49acf90684.png)
