### ISSUE TITLE
Can't filter on files located in dir without write permission

### ISSUE THREAD

**Issue by yhd4711499** [everettjf/vscode-filter-line#3]
As the title goes.

```
[Extension Host] output : /private/var/log/system.log.filterline.log
workbench.main.js:sourcemap:1376   ERR EACCES: permission denied, open '/private/var/log/system.log.filterline.log': Error: EACCES: permission denied, open '/private/var/log/system.log.filterline.log'
```

**Comment by everettjf** [comment]
腾讯大佬？！哈。直接中文了额。。
这个插件会在要过滤的文件的相同目录创建一个文件（原文件名加上filterline.log）。
这个逻辑的话，那就是创建这一步失败了。

如果要解决这个问题，
1. 复制出来，到有可写权限的目录下。（废话哈哈，但可以先临时解决问题）
2. 或者插件可以提供一个参数，不在相同目录下创建这个临时文件。（需要修改插件）

难得有相同需求的同胞，可以微信聊哈哈。微信：everettjf

---

English translate : 

1. Copy the target file to a writable directory.
2. The plugin provide a new config ( for create tmp file in a specified directory) .

**Comment by yhd4711499** [comment]
谢谢你的快速答复。用中文倒不是不行，只是github是一个全球的社区，如果用中文的话，老外们就看不懂了，所以，能英文的就英文吧 ; )

This usecase is not quite common I suppose. So I can live with the `copy solution` : )

Btw, I was searching for a tool like `AnalysePlugin` on notepad++, which supports multiple filters. Sadly there is no alternatives on macOS. Fortunately your plugin is quite a promising one.

**Comment by everettjf** [comment]
Thanks for your seriousness.
Hopefully you enjoy it.
