### ISSUE TITLE
File locked?

### ISSUE THREAD

**Issue by adampaquette** [everettjf/vscode-filter-line#4]
1 - I filter a text by string, it works the first time.
2 - A new file get created.
3 - I return to the original file and do a filter again with the same pattern and nothing is shown.

The newly created file says I need to be admin to delete it, I am admin.
The file can be seen on my desktop and when I try to delete it, it says, it dosen't exists.

I run VS Code as admin.

**Comment by everettjf** [comment]
1. What system ? macOS or Windows ?
2. How to run under admin ? sudo?

**Comment by adampaquette** [comment]
Windows 10
I right click on the executable location witch is ""C:\Users\apaquette\AppData\Local\Programs\Microsoft VS Code\Code.exe" and do a right click run as Admin.

**Comment by everettjf** [comment]
I can reproduce the problem and looking into it.

**Comment by everettjf** [comment]
The file owner is "..." and even the administrator command line can not open it.
![image](https://user-images.githubusercontent.com/1665109/45789525-b6179700-bcb2-11e8-98fa-2730e9394f29.png)

Guess : Same like that the extension is running in another special privilege process when vscode is opened by administrator, and the file created by the extension can not be deleted by the creator.

**Comment by adampaquette** [comment]
Could it be possible to : 

1. Don't force the save of the current current tab.
2. Open the filtered data into an other in memory tab and let the user decide what to do with the result?

In my case, I don't want to save the results.

**Comment by everettjf** [comment]
Yes, it can be. But the new way change the convention the extension does currently, and in my situation the log file is too large to put into memory. Maybe there could be an config.
And I want to know the situation that you must run vscode under administrator ?

**Comment by adampaquette** [comment]
I don't have to run as Administrator but I wanted to make sure the error I had was not relevant to admin access privilèges.

And Yes, a config would do it ;)

BTW : I think this plugin should be built-in VS Code. I have many features requests. Want me to open an issue for each?

**Comment by everettjf** [comment]
1. It is a bug under admin access privileges. Since you do not have to run as administrator, the fix plan could be delayed :)
2. Yes, welcome to open issues. I wanna to know :)
