### ISSUE TITLE
The filterline file is empty and isn't open 

### ISSUE THREAD

**Issue by java9394** [everettjf/vscode-filter-line#5]
I installed the Filter Line 1.1.0 extension.
I open the command palette, enter a string to filter the file.  I saw a xxx.filterline.xx file was generated along with my original file, but the file is empty (0 size), and it didn't get open on the VSCode editor.  Any idea?

thx

Steve

**Comment by everettjf** [comment]
Could you provide more detail about the file's content and the string you input ?

**Comment by java9394** [comment]
I reinstalled the VSCode, the problem went away.  

thx.

Steve
