### ISSUE TITLE
Unicode Character “□” (U+25A1)

### ISSUE THREAD

**Issue by cpalafoutas1** [everettjf/vscode-filter-line#7]
Not so much an issue as an FYI
I had a log file with a bunch of □'s in it and it seemed to mess up the results.  I found 85 instances of a string in my file but your filter by string gave me only 25.  It also gave me too few when I filtered by not contain string.  When I deleted all the □'s it worked fine.  In this case I had work around but not sure if you have had other issues with Unicode characters.

**Comment by everettjf** [comment]
Could you send me that file ? Or parts of that file ?

**Comment by cpalafoutas1** [comment]
[console-20190204.log](https://github.com/everettjf/vscode-filter-line/files/2841869/console-20190204.log)

**Comment by everettjf** [comment]
Thanks. I will try to fix it in the next version in about 2 days.

**Comment by everettjf** [comment]
@cpalafoutas1 Hi, I tried with the file https://github.com/everettjf/vscode-filter-line/blob/master/demo/logsymbol/console-20190204.log , but I can not find the symbol □.

How could I reproduce the bug step by step with that file? 
Please tell me more.

And v1.2.2 has been published just now, you could try the new version.

**Comment by cpalafoutas1** [comment]
It said I had the latest version but I saw that you made a recent commit, so I removed it and reinstalled it and I am not getting the issue on the original file.  Filter by string returns the same number as search.

I'm having trouble still with the attached file, which is smaller than the original.  It's returning 0 rows.
I opened the file in Visual Studio, opened the command palette, selected filter by string, entered Brute and hit enter.  There should be 18 rows returned.

I noticed when I look a the file in GitHub it shows the squares, but when enter edit mode they display as red dots.

**Comment by everettjf** [comment]
@cpalafoutas1 on my macOS, there are no squares. Got it , you are on Windows system.
I will find a Windows and test it.

**Comment by everettjf** [comment]
For now, you could try to change the encoding:
click right bottom 'UTF-8'(may be different on Windows), and input UTF-8 in the input box.
![image](https://user-images.githubusercontent.com/1665109/52610806-a2690900-2ebd-11e9-8961-002853ba02d0.png)

**Comment by everettjf** [comment]
Hi, I have tested by your method on Windows.
But it works.
![image](https://user-images.githubusercontent.com/1665109/52803829-cdba4680-30bd-11e9-9c3b-1424e6de13ec.png)
