### ISSUE TITLE
Cannot filter for string containing the plus (+) symbol

### ISSUE THREAD

**Issue by jamilraichouni** [everettjf/vscode-filter-line#8]
"Filter Line By Input String" is not working when my input string contains a '+' symbol.

I was after all key bindings containing 'alt+' but could not filter for that.

Filtering for 'ctrl+' or 'shift+' is also not working.

**Comment by everettjf** [comment]
Hi, I have tried with this file https://github.com/everettjf/vscode-filter-line/blob/master/demo/logplus/log.log  ,but still can not reproduce the bug.
Please tell me more.

And please confirm that you are filtering line by input `String` , not `Regular Expression`.

**Comment by jamilraichouni** [comment]
Hi!

Using that example and "Filter Line By Input **String**" using just a '+' as search string doesn't work for me. I can show that via Skype or Teamviewer if you like. I'm located in Germany and can demonstrate that in the afternoon or evening.

Cheers

**Comment by everettjf** [comment]
Does this log file https://github.com/everettjf/vscode-filter-line/blob/master/demo/logplus/log.log still not work?
Could you upload an example log file ?

**Comment by jamilraichouni** [comment]
Exactly. I copied the text from your log file into some temporary file and opened it in VSC.
Then I chose "Filter Line By Input **String**" from the command palette and used just a '+' as search string and hit ENTER. Nothing happens. The content of the text editor keeps being the same including lines 7; 9-10;16-18. Hence, it does not filter and does not show the lines containing a '+' only as I expect it.

**Comment by jamilraichouni** [comment]
Does your extension produce a .log file? If so: Where do I find it?

**Comment by everettjf** [comment]
Yes, it products a 'filename.filterline.extension' file.( e.g. if you filter foo.log , it will product foo.filterline.log)
![image](https://user-images.githubusercontent.com/1665109/52802818-a95d6a80-30bb-11e9-89d9-c3caeb67edee.png)

**Comment by everettjf** [comment]
I have tested the + search on macOS and Windows, and still can not get the bug.
![image](https://user-images.githubusercontent.com/1665109/52802894-cabe5680-30bb-11e9-9deb-735f775d35af.png)
![image](https://user-images.githubusercontent.com/1665109/52802913-d447be80-30bb-11e9-8687-65dc945da662.png)
![image](https://user-images.githubusercontent.com/1665109/52802923-dad63600-30bb-11e9-9687-bd434615e241.png)

**Comment by everettjf** [comment]
Anything different with screenshots above？

**Comment by everettjf** [comment]
Hi @jamilraichouni , if the bug still exists. I can use Skype in the evening.
11:00 to 12:00 PM (GMT+8)
Time in Beijing, China
